# ===== LLVM PATHS =====
LLVM_PATH = $(HOME)/git/tud/build-ll/bin/

# ===== PASSES PATHS =====
TX_PATH  = $(HOME)/git/tud/haft/src/tx/
ILR_PATH = $(HOME)/git/tud/haft/src/ilr/

# ===== ADDITIONAL FLAGS =====
# version of HTM to use -- tx_debug.c  tx_ibm.c  tx_intel.c
TX_VERSION = tx_intel.c

# flags for Hardware Transactional Memory used
HTM_FLAGS = -mrtm     # uncomment for Intel TSX


